### PR TITLE
Feature/add uart

### PR DESCRIPTION
**Pull request by Craques**
- Added UART module

### CODE REVIEW

**Comment by jpt13653903** [comment]
Glad you closed it -- there is no way I'm merging this ;-)

**Comment by Craques** [comment]
Sorry for that, realized i was pointing to the wrong master when I created this PR

**Comment by jpt13653903** [comment]
I figured :-)
No worries

**Comment by Craques** [comment]
I left a question here https://github.com/Craques/UCT-FPGA-Course-2022/pull/3 with regards to the test bench, for the RX side I would need to know what the data is beforehand, how can one simulate that?

**Pull request closed without merging**
